/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noe-3d.at (https://sketchfab.com/www.noe-3d.at)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/lowe-46eea1a922bd433a935351e7c2eff652
Title: Löwe
*/

import React, { forwardRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh, Material, Group } from "three";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: Mesh;
    Object_3: Mesh;
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
    Object_7: Mesh;
    Object_8: Mesh;
  };
  materials: {
    Loewe2_O_Material_u1_v1: Material;
    bottom: Material;
  };
};

const Lion = forwardRef<Group, React.ComponentPropsWithoutRef<"group">>(
  function Lion(props, ref) {
    const { nodes, materials } = useGLTF(
      "/3d/lion.glb"
    ) as unknown as GLTFResult;
    return (
      <group ref={ref} {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.Loewe2_O_Material_u1_v1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.bottom}
        />
      </group>
    );
  }
);

export default Lion;

useGLTF.preload("/3d/lion.glb");
