/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: abhayexe (https://sketchfab.com/abhayexe)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/giant-scifi-statue-069dd59c2f4a4b08b9649aabc3e4f5e1
Title: Giant Scifi Statue
*/

import { useLoadingStore } from "@/stores/loadingStore";
import { useGLTF } from "@react-three/drei";
import { BufferGeometry, Mesh, MeshStandardMaterial, Scene } from "three";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";
import React, { useEffect, useRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: Mesh;
  };
  materials: {
    Stone_wall: MeshStandardMaterial;
  };
  scene: Scene;
};

interface MenuStatueProps extends React.ComponentPropsWithoutRef<"group"> {
  metalness?: number;
  roughness?: number;
}

export default function MenuStatue({
  metalness = 0.55,
  roughness = 0.75,
  ...props
}: MenuStatueProps) {
  const { nodes, materials, scene } = useGLTF(
    "/3d/menu-statue.glb"
  ) as unknown as GLTFResult;

  const { setAssetLoaded } = useLoadingStore((state) => state.actions);

  const hasReportedLoadRef = useRef(false);

  useEffect(() => {
    if (scene && !hasReportedLoadRef.current) {
      setAssetLoaded("menuStatue");
      hasReportedLoadRef.current = true;
    }
  }, [scene, setAssetLoaded]);

  useEffect(() => {
    if (materials.Stone_wall) {
      materials.Stone_wall.metalness = metalness;
      materials.Stone_wall.roughness = roughness;
      materials.Stone_wall.needsUpdate = true;
    }
  }, [materials, metalness, roughness]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry as BufferGeometry}
        material={materials.Stone_wall}
        position={[0, 2.457, -2]}
      />
    </group>
  );
}

export function MenuStatueLoader() {
  const { scene } = useGLTF("/3d/menu-statue.glb");
  const { setAssetLoaded } = useLoadingStore((state) => state.actions);

  useEffect(() => {
    if (scene) {
      setAssetLoaded("menuStatue");
    }
  }, [scene, setAssetLoaded]);

  return null;
}

useGLTF.preload("/3d/menu-statue.glb");
