/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: abhayexe (https://sketchfab.com/abhayexe)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/giant-scifi-statue-069dd59c2f4a4b08b9649aabc3e4f5e1
Title: Giant Scifi Statue
*/

import { useLoadingStore } from "@/stores/loadingStore";
import { useGLTF } from "@react-three/drei";
import { BufferGeometry, Mesh, MeshStandardMaterial, Scene } from "three";
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js";
import React, { useEffect, useMemo, useRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: Mesh;
  };
  materials: {
    Stone_wall: MeshStandardMaterial;
  };
  scene: Scene;
};

interface MenuStatueProps extends React.ComponentPropsWithoutRef<"group"> {
  metalness?: number;
  roughness?: number;
}

export default function MenuStatue({
  metalness = 0.0,
  roughness = 0.35,
  ...props
}: MenuStatueProps) {
  const { nodes, materials, scene } = useGLTF(
    "/3d/menu-statue.glb"
  ) as unknown as GLTFResult;

  const { setAssetLoaded } = useLoadingStore((state) => state.actions);

  const hasReportedLoadRef = useRef(false);

  // Clone the original material to preserve normal maps for detail, but remove color textures
  const material = useMemo(() => {
    if (!materials.Stone_wall) return null;
    const clonedMaterial = materials.Stone_wall.clone();
    // Remove color-affecting textures to eliminate yellowish/greenish tint
    clonedMaterial.map = null; // Remove diffuse/color map
    clonedMaterial.aoMap = null; // Remove ambient occlusion map that might tint
    clonedMaterial.emissiveMap = null; // Remove emissive map
    // Keep normal map for surface detail (eyes, etc.)
    // Keep roughnessMap and metalnessMap if they exist for realistic shading
    // Modify to realistic statue appearance
    clonedMaterial.color.set("#f0ede5"); // Warm off-white marble color
    clonedMaterial.metalness = metalness;
    clonedMaterial.roughness = roughness;
    clonedMaterial.envMapIntensity = 0.5; // Subtle environment reflections
    clonedMaterial.needsUpdate = true;
    return clonedMaterial;
  }, [materials]);

  useEffect(() => {
    if (scene && !hasReportedLoadRef.current) {
      setAssetLoaded("menuStatue");
      hasReportedLoadRef.current = true;
    }
  }, [scene, setAssetLoaded]);

  useEffect(() => {
    if (material) {
      material.metalness = metalness;
      material.roughness = roughness;
      material.needsUpdate = true;
    }
  }, [material, metalness, roughness]);

  if (!material) {
    return <group {...props} dispose={null} />;
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry as BufferGeometry}
        material={material}
        position={[0, 2.457, -2]}
      />
    </group>
  );
}

export function MenuStatueLoader() {
  const { scene } = useGLTF("/3d/menu-statue.glb");
  const { setAssetLoaded } = useLoadingStore((state) => state.actions);

  useEffect(() => {
    if (scene) {
      setAssetLoaded("menuStatue");
    }
  }, [scene, setAssetLoaded]);

  return null;
}

useGLTF.preload("/3d/menu-statue.glb");
