export const products = [
  {
    slug: "whey-isolate",
    name: "Whey Isolate",
    description: "The best protein for muscle growth.",
    price: 49.99,
    salePrice: 29.99,
    flavor: ["Vanilla", "Chocolate", "Strawberry"],
    size: ["600g", "900g", "1200g"],
    image: "/images/whey-protein.jpg",
    href: "/product/whey-isolate/",
    reviewsLength: 93,
  },
  {
    slug: "creatine",
    name: "Creatine",
    description: "Boost strength and power.",
    price: 39.99,
    salePrice: 19.99,
    flavor: ["Unflavored", "Fruit Punch", "Blue Raspberry"],
    size: ["300g", "600g"],
    image: "/images/creatine.jpg",
    href: "/product/creatine/",
    reviewsLength: 111,
  },
  {
    slug: "pre-workout",
    name: "Pre Workout",
    description: "Recover faster and build more muscle.",
    price: 24.99,
    salePrice: 18.99,
    flavor: ["Fruit Punch", "Blue Raspberry", "Watermelon"],
    size: ["300g"],
    image: "/images/object-img.jpg",
    href: "/product/pre-workout/",
    reviewsLength: 37,
  },
]

export const discountCode = "ETHERA"
